### ISSUE TITLE
Self-Contained Binary Versions 

### ISSUE THREAD

**Issue by harrypm** [samuelncui/yatm#2]
Pre-compiled self contained versions ready and easy to deploy would make this project far more adoptable, very much so for people already with windows/macos file servers with LTO drives as Linux support with LTFS is iffy but MacOS and with some issues windows has better support for end users.

Checklist:

- [x] MacOS
- [x] MacOS Arm 
- [x] Linux  
- [x] Linux Arm
- [ ] Windows
- [ ] Windows Arm

With the new Pi 5 PCIe support, this would be amazing to intergrate into a low power Tape server on the ARM platform for example with apple moving to there own ARM based hardware its growing rapidly adoption wise.

**Comment by samuelncui** [comment]
Currently, I have provided Linux amd64 binary. The problem is I don't have a Mac / Windows device that can connect tape drive. At its current state, this software theoretically can run on a unix-like system. But because of the big difference of mount mechanism, running it on Windows maybe more difficult. I would try to compile macOS and Linux arm binary, but unfortunately can't test them.

**Comment by samuelncui** [comment]
And as far as I know, Pi 5's PCIe only supports gen2/3 x1, and it only has one 1Gbps Ethernet port. Tbh Orange Pi 5 Plus with 2x M2 and 2.5Gbps Ports might be more suitable for the job (if its m2 can be converted to pcie).

**Comment by harrypm** [comment]
@samuelncui you should leverage community testing for this, untill you can build a couple test boxes or a proxmox station.

I can test windows, and possibly arm on a RockPro64.
